import type { Metadata } from "next";
import { ReactNode } from "react";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.scss";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--body-font",
  fallback: ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
  display: "swap"
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--heading-font",
  fallback: ["Trebuchet MS", "Helvetica", "Arial", "sans-serif"],
  display: "swap",
});

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html 
      lang="en"
      suppressHydrationWarning 
      data-scroll-behavior="smooth"
      className={`${openSans.variable} ${poppins.variable}`}
    >
      <body>
        <main className="app">
          {children}
        </main>
      </body>
    </html>
  );
};

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
export { metadata };